version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $IMAGE_REPO_AWS_REGION)
  build:
    commands:
      - bin/build
      - docker tag built $IMAGE_REPO_URL:latest
  post_build:
    commands:
      - docker push $IMAGE_REPO_URL:latest
